### ISSUE TITLE
config() not found in Laravel 4.2

### ISSUE THREAD

**Issue by ericsala** [stevebauman/translation#1]
helpers.php use config() function. 

This function is only available in Laravel 5. Why not use Config::get alternative?

Thank you!

**Comment by stevebauman** [comment]
Woops! Apologies for this, I made a custom config function helper in one of my other packages and forgot that Laravel 4 doesn't have a config function helper. Will be fixed shortly. 

Thanks!

**Comment by ericsala** [comment]
Thank you for your work ;-)

**Comment by stevebauman** [comment]
Fixed! https://github.com/stevebauman/translation/commit/4415f1dc2ae58a32202f20944e41beb69c96033a

No problem at all, let me know if you experience any other issues.
