### ISSUE TITLE
route prefix and middleware not work with resource controller routes

### ISSUE THREAD

**Issue by herzcthu** [stevebauman/translation#11]
I have route like below.
```php
Route::group(['prefix' => Translation::getRoutePrefix(), 'middleware' => ['locale']], function()
{
    Route::group(['namespace' => 'Frontend'], function ()
    {
       Route::group(['middleware' => 'auth'], function ()
       {
           Route::resource('profile', 'ProfileController', ['only' => ['index','edit', 'update']]);
       });
    });
});
```
But when I use route method in view or controller like route('profile.index'); and access with language prefix, I got route not defined error.
http://localhost/profile is ok but http://localhost/fr/profile is not ok.

But if I use url method like url('profile'), it work.

**Comment by stevebauman** [comment]
Really sorry for the long response on this issue!

I just tested this and it works as expected. Make sure you have `fr` in your `locales` array inside your `config/translation.php` file.

**Comment by stevebauman** [comment]
Closing until a further follow up.
