### ISSUE TITLE
stichoza/google-translate-php compatibility

### ISSUE THREAD

**Issue by donnyt** [stevebauman/translation#13]
Hi,

I get this issue when running composer update

Problem 1
    - stevebauman/translation v1.3.2 requires stichoza/google-translate-php 3.0.* -> no matching package found.
    - stevebauman/translation v1.3.1 requires stichoza/google-translate-php 3.0.* -> no matching package found.
    - stevebauman/translation v1.3.0 requires stichoza/google-translate-php 3.0.* -> no matching package found.
    - Installation request for stevebauman/translation 1.3.* -> satisfiable by stevebauman/translation[v1.3.0, v1.3.1, v1.3.2].

Is your package compatible with the latest stichoza/google-translate-php ~3.2?

Thanks,
Donny

**Comment by stevebauman** [comment]
Hi @donnyt, this package requires stichoza/google-translate-php v3.0.*. You won't be able to install it with having a new version of google-translate-php currently installed. I'll update it with the new version shortly.

**Comment by donnyt** [comment]
Thanks @stevebauman!

**Comment by stevebauman** [comment]
Just updated to version `v3.2.*` of stichoza's google translate php. You should be all set!
