### ISSUE TITLE
Issue when changing translations in database

### ISSUE THREAD

**Issue by catalinrosu** [stevebauman/translation#14]
First of all thanks for such a great package, I use it and it's very easy to have translations already done with google. Great job.

I also think there is a small issue when trying to change the translation texts from the database. I have "auto_translate" option set to "true", and sometimes the google translation is not quite good, so every time I change the translation text in the model table, it generates me another row in the model table with the same Google translation as before. Of course i clear cache every time I make a change.

I have seen your code and you make a firstOrCreate with the google translation, but this query is not going to find the changes made on translations manually, so I think first you have to check if there is a result with a locale_id and translation_id and then make a creation query in case of no result.

I think you should consider it, or maybe you already did and I don't get it right.
I wait for your reply. Thanks in advance.

Best regards.

**Comment by stevebauman** [comment]
Hi @catalinrosu, you're right, this shouldn't happen. It should look to see if a translation exists first then create one if it doesn't. Going to fix this.

**Comment by LucanFahr** [comment]
I can add the following to this;

I had it set to auto-translate first, then filled the database that way. I turned off auto-translate and cleared the cache. Next reload, it created NEW entries for all existing items with the default locale.

I tried to fix this by setting a UNIQUE key on the locale_id + translation_id fields (it SHOULD be unique, I think), after removing the strange entries. The next reload gave me a duplicate key error.

This does not appear to be solely a problem with the auto translation. Even when turned off, it re-creates the translations over and over again. It seems the lookup fails and it just re-inserts them.

**Comment by stevebauman** [comment]
Just pushed out a commit (https://github.com/stevebauman/translation/commit/191ffbf26df710a52d2576a9b1d53449f6b57016) to fix these issues. Definitely a huge oversight on my part!

Please try updating to the new release and let me know if you encounter these issues still.

**Comment by LucanFahr** [comment]
Well... I updated, cleared the DB, cleared the cache, re-ran the migrations and now it seems it only creates 1 entry per language... The last _t(' ') block on the page is the only one that is picked up and all texts are turned into it.

I guess instead of NOT finding the translation, it now ALWAYS finds it - as the very first one.

**Comment by LucanFahr** [comment]
Suggested fix:

```php
        $translationFields = [
            $locale->getForeignKey() => $locale->getKey(),
            $this->translationModel->getForeignKey() => (isset($parentTranslation) ? $parentTranslation->getKey()  : null)
        ];

        if(!isset($parentTranslation))
        {
            // Also include text, so it does not trigger on all translation_id = NULL for initial translations
            $translationFields['translation'] = $text;
        }

        $translation = $this->translationModel->firstOrNew($translationFields);
```

**Comment by stevebauman** [comment]
Yup you're right, pushed out a new release. Apologies.

Please update and let me know if you encounter any issues, thanks!

**Comment by LucanFahr** [comment]
This seems to work quite well indeed. Thanks for the quick follow-up!

**Comment by LucanFahr** [comment]
One other thing I did notice is that the cache now no longer appears to be working... though I might be wrong. I changed some text in the DB and it instantly showed up on the site after a reload. Not sure if there is something there. Either way - this works great!

**Comment by stevebauman** [comment]
Great! No problem at.

Hmm, cache seems to be working completely fine for me. I'll write some more tests, but if you encounter any problems please create another issue and I'll address that separately, thanks!

**Comment by stevebauman** [comment]
You're right @LucanFahr, translated records aren't being retrieved from the cache correctly. Going to create an issue for this and have a fix shortly, thanks!
