### ISSUE TITLE
Parent translation

### ISSUE THREAD

**Issue by catalinrosu** [stevebauman/translation#18]
Hello Steve,
I believe the function parent in Translation Model needs to be changed, it doesn't return anything as it is.
It should be like this:

`public function parent()
    {
        return $this->belongsTo(self::class, 'translation_id');
    }`

What do you think?. Thanks.

**Comment by stevebauman** [comment]
Hi @catalinrosu, apologies for the long response.

The relationship works as intended. Tested just now.

The change would be identical to what's already in place. The `getForeignKey()` method on the model camel cases the current classes name with a suffix of '_id', so the end result is 'translation_id'.
