### ISSUE TITLE
Interface for paid Translate API / other translation packages

### ISSUE THREAD

**Issue by stevethomas** [stevebauman/translation#21]
This package ticks many boxes, except having the translation client hard coded means I can't use the paid Google API. 

If the translate client was implementing as an interface and resolved through the config file instead, is this a direction you would want to go in? I guess this also means a wrapper would be required for stichoza/google-translate-php so the interface is implemented.

That would obviously also open up doors for other translation providers like Bing.

**Comment by stevebauman** [comment]
Yea this is definitely something I'm interested in implementing. I only thought about free solutions and completely forgot about paid API access.

I'll see what I can put together :).

**Comment by stevethomas** [comment]
Excellent! I'm happy to contribute, perhaps if you could commit an interface class then I can build a paid API implementation?

**Comment by stevethomas** [comment]
@stevebauman,

I've made some changes and it now works with the paid Google Translate API. I'm wondering if you could take a look and provide some feedback?

There are a couple of potential issues / things that maybe should be addressed before sending a PR:

1. I couldn't think of a good way to pass the API key to the test suite, given that tests have no awareness of the config file. If you manually set a valid API key in getEnvironmentSetUp(), and also set the client to the GooglTranslateApi, all tests pass. 
2. The paid API should probably be a self-contained package with tests, it would just require another wrapper as I don't think it would make sense implementing the Client Interface in an external package. I did look for a pre-existing package for the Google Translate API but couldn't find one that was of sufficient quality. 

https://github.com/stevebauman/translation/compare/master...stevethomas:bugfix

**Comment by stevebauman** [comment]
@stevethomas This is great work! Apologies for the long response.

> I couldn't think of a good way to pass the API key to the test suite, given that tests have no awareness of the config file. If you manually set a valid API key in getEnvironmentSetUp(), and also set the client to the GooglTranslateApi, all tests pass.

That's fine and is expected. Couldn't we just mock out the client interface during testing and assert certain parameters?

> The paid API should probably be a self-contained package with tests, it would just require another wrapper as I don't think it would make sense implementing the Client Interface in an external package. I did look for a pre-existing package for the Google Translate API but couldn't find one that was of sufficient quality.

I don't see the issue with having multiple clients in the self-contained package with tests? We don't necessarily need an API key if we just test that the methods are sending / receiving the right parameters?

For example, for Laravel's tests of cache providers, he mocks the provider and asserts that the right methods are called and the correct params are sent:

https://github.com/laravel/framework/blob/5.2/tests/Cache/CacheRedisStoreTest.php

**Comment by stevethomas** [comment]
> I don't see the issue with having multiple clients in the self-contained package with tests?

Fair point. That is after all the approach of Monolog and a bunch of other packages. I guess in some cases the client could be wrapped as I did with TranslateClient, in other cases we would have to write our own implementation. I don't think there are more than a handful of translation providers out there anyway.

> Unless of course I'm misunderstanding your concerns.

You are not; I'm a little green when it comes to mockery / testing. 

I'll give it a try and send through a PR.

**Comment by stevethomas** [comment]
suggest tagging release 1.4.o with these commits

**Comment by stevebauman** [comment]
Done! Thanks again :)
