### ISSUE TITLE
Locale / Translation manager

### ISSUE THREAD

**Issue by brunogaspar** [stevebauman/translation#25]
Hello @stevebauman 

Have you built a locale/translation manager with this?

I'm currently building one, but it seems that this package was not really well designed to be handled through a web interface.

So i'm wondering if you or any one else has built this.

**Comment by stevebauman** [comment]
Hi @brunogaspar, I haven't built one, but with the included models I don't see why it can't be done.

**Comment by stevebauman** [comment]
Woops, apologies, didn't mean to close this, I'll leave this open for anyone else to chime in if they've implemented anything.

**Comment by brunogaspar** [comment]
Thanks for the input and no problem on closing heh.

--

I don't think a translation manager will really work for my needs.

The reason is, i'm currently using gettext on this application, which works quite nice, and is hella fast but i want to introduce modularity to this application, so gettext is not going to really work as expected, as i would need to look into merge `.po` files and possible a way to synchronize them..ugh lol

Hence the why i'm looking for alternatives to gettext and to the way Laravel handles this, because let's face it `{{ trans('button.save') }}` is not as expressive as `{{ _t('Save') }}`.

One stopping point that i got so far was that if i want to share a file or even files to be translated later, i can't really do it with this package (it was not designed for this, which is understandable), while with the `.po` files it's quite easy.

I though about having a namespace column on the translations table, so i could have exporter and importer command to generate a file that could be easily translated, but how would that namespace column be filled up?

Do you have any suggestions for my use case?

Keep in mind that i understand that this package was not designed for this.

**Comment by Quadriphobs1** [comment]
Hi@stevebauman @brunogaspar, Sorry to come in here, has anyone one of you actually implement this in a Language Translation Manager,
