### ISSUE TITLE
Configuration

### ISSUE THREAD

**Issue by gilbert1995** [stevebauman/translation#3]
Hi I'm on Laravel 4 and I got this error everytime

Stevebauman \ Translation \ Exceptions \ InvalidLocaleCodeException
Locale Code: fr is invalid, please make sure it is available in the configuration file

and I'm not sure how I can fix

Thanks for your help

**Comment by stevebauman** [comment]
Hi, have you published the configuration file?
On Jun 19, 2015 11:40 PM, gilbert1995 <notifications@github.com> wrote:Hi I'm on Laravel 4 and I got this error everytime

Stevebauman \ Translation \ Exceptions \ InvalidLocaleCodeException
Locale Code: fr is invalid, please make sure it is available in the configuration file

and I'm not sure how I can fix

Thanks for your help

**Comment by gilbert1995** [comment]
Yes I make this command: "php artisan config:publish stevebauman/translation"
PS this is not in installation note

**Comment by stevebauman** [comment]
Hi sorry for the long response on this, please update to `v1.2.3`. This should be fixed. Please post back if you still have this issue, thanks!
