### ISSUE TITLE
Changing locale in routes doesn't make effect

### ISSUE THREAD

**Issue by vedmant** [stevebauman/translation#4]
When I try to change locale based on URL prefix in routes like "/en/page" it doesn't save new value to session. It always uses first value saved to session and doesn't change it afterwards. I tried "database", "file", "cookie" driven sessions, it works only with "array" driven session, but "array" driver can be "not be persisted across requests". 

Is it possible to add options not to save locale to session, but instead just save it in class instance property? It would solved my problem.

Thanks.

**Comment by stevebauman** [comment]
This is an issue with Laravel itself. Setting a session key the routes file is hit or miss depending on the driver it seems.

See:

https://github.com/stevebauman/translation#issues & https://github.com/laravel/framework/issues/8244

**Comment by vedmant** [comment]
Thank you, I visited previously this links. I just think that storing locale in session by default is not a good idea, maybe it's better to let developer choose how he wants to set locale (through session, URL section, query parameter, so on).

**Comment by stevebauman** [comment]
Storing the users locale in a session key is a pretty widespread practice, but you're right, it'd be nice to have choice rather then rely on the session :+1: . I'll work on this. However, you're absolutely free to set the locale wherever you like, and I'd really recommend setting it inside a Middleware so you can access the route and the parameter itself for easy manipulation.

**Comment by vedmant** [comment]
Thanks! Yes, I've already implemented it thought Middleware, however I'm still fighting some bugs as routes are processed before middleware so I have keep extra code in routes anyway.

**Comment by stevebauman** [comment]
No problem! Would you be able to share the bugs you're encountering with the middleware?

**Comment by vedmant** [comment]
Problems come when I want to use URL without language prefix with default language (meaning "/auth/register" is English while "/de/auth/register" is German. I had to use Middleware only to set locale for this module:

    public function handle($request, Closure $next)
    {
        $lang = $request->segment(1);
        $languages = array_keys(Config::get('translation.locales'));

        if (in_array($lang, $languages)) {
            Translation::setLocale($lang);
        } else {
            Translation::setLocale(Config::get('translation.default'));
        }

        return $next($request);
    }

And this is my routes file for now:

    $locale = Request::segment(1);
    $languages = array_keys(Config::get('translation.locales'));
    unset($languages[array_search(Config::get('translation.default'), $languages)]);
    if (! in_array($locale, $languages)) {
        $locale = null;
    }

    Route::group(['prefix' => $locale, 'middleware' => 'locale'], function () {

        Route::get('/', ['uses' => 'HomeController@home']);

        Route::controller('auth', 'AuthController');

    });

So much efforts just for this simple task, I'm novice to Laravel, but with Kohana framework I used before this all was much more simple.

Also I have some problems with Chinese translations, they fill automatically with wrong UTF-8 characters and sometimes it just doesn't show any translations at all (but in DB I see them). I think maybe it's SqLite problem, if no I will have to dig this issue too.

**Comment by stevebauman** [comment]
Why don't you use the optional route parameter? http://laravel.com/docs/5.1/routing#route-parameters

    Route::group(['prefix' => '{locale?}', 'middleware' => ['locale']], function ()
    {
    
    });

Inside your middleware you can then perform the validation if the inserted parameter is a valid locale. This would solve your issue.

    public function handle($request, Closure $next)
    {
        $locale = $request->route('locale');
    }

Also about the Chinese translations, I've never played with storing those types of languages, so you'll most likely need to modify the migration.

**Comment by vedmant** [comment]
I tried, but it doesn't work with default language without locale section, like "/auth/register", it passes "auth" as locale param and then it can't find route "register", it removes "auth" segment inside route group. So I need to specify explicitly what to expect in this segment: one of languages code from languages array.

**Comment by stevebauman** [comment]
Ahh yea you're right. Hmm..

**Comment by vedmant** [comment]
It was quite easy with Kohana framework:

    Route::set('default', '(<lang>/)(<controller>(/<action>(/<id>)))', array('lang' => $allowed_langs))
        ->defaults(array(
            'lang'       => $default_lang,
            'controller' => 'landing',
            'action'     => 'index',
        ));

but Laravel routes are really tough...

**Comment by stevebauman** [comment]
Never tried Kohana, but that looks pretty flexible. You're right though, this is tricky to perform in laravel. I've worked with mandatory locale parameters (`en/page`, 'fr/page`), but never optional ones. I'll see if there's a way I can bake this into translation.

**Comment by vedmant** [comment]
Thank you, it would be really helpful as most of times I was asked to remove default language prefix from URL. I will add request for Laravel framework to add parameters to optional routes prefixes or Regex pattern, so if it matches then it captures prefix, otherwise it passes URI to group as is.

**Comment by stevebauman** [comment]
Hi @vedmant, I've fixed the issue with Chinese and all other UTF-8 characters. The issue was simply running `ucfirst()` on the translated text, and that function isn't compatible with UTF-8.

Also, you can install `dev-master` and test out the new route functionality if you'd like.

How to set it up:

In your routes:

    Route::group(['prefix' => Translation::getRoutePrefix(), 'middleware' => ['locale']], function()
    {
        
    });

Add the Locale middleware to your `Kernel.php`:

    /**
     * The application's route middleware.
     *
     * @var array
     */
    protected $routeMiddleware = [
        'auth' => \App\Http\Middleware\Authenticate::class,
        'auth.basic' => \Illuminate\Auth\Middleware\AuthenticateWithBasicAuth::class,
        'guest' => \App\Http\Middleware\RedirectIfAuthenticated::class,

        // Here
        'locale' => \Stevebauman\Translation\Middleware\LocaleMiddleware::class
    ];

**Comment by vedmant** [comment]
Wow, great! I'll check it!

**Comment by stevebauman** [comment]
Great! Also, the method `getRoutePrefix()` will return null if the locale code does not exist in your `translation.php` file, and it will use your default application locale in that case so you're able to have no locale parameter inside your routes like you were wanting.

**Comment by vedmant** [comment]
There is one problem, if I remove 'en' => 'English', from configuration file it stops working (after ./artisan migrate:refresh and cache:clear): "Locale Code: en is invalid, please make sure it is available in the configuration file". But if I leave English there it will be URL duplicate "/auth/register" and "/en/auth/register".

**Comment by stevebauman** [comment]
Ahh you're right. Okay try it now

**Comment by vedmant** [comment]
Great, it works good now! 

Also one point, it will now support only English as default language (URL without prefix). For my purposes it's ok, but in other case it may require different language as default. I think following will be good approach, instead of removing 'en' language from config file it can just unset from $locales default language and (from app config). This can be optional with additional setting in configuration file like 'no_prefix_for_default_locale', or something like this.

Also, I think it might be a bug, I tried to set in config app.locale 'de' (and reset DB and cache), it sets 'de' locale successfully, adds to locales table 'de' as first record, but doesn't translate automatically strings to German, just sets them from translate method.

Thanks!

**Comment by stevebauman** [comment]
Yea that's true, that would be a good configuration option to have, I'll work that in shortly! Also I'll try to play with that and see if I can reproduce this. Still have to refactor the whole class since it's pretty messy in my opinion. Upcoming release will be 2.0 since I'm ending L4 support.

Thanks for all your input!

**Comment by vedmant** [comment]
I just come up with idea, maybe there is a sense to introduce new one locale called something like 'source'. It will store initial strings, passed to translation function. This way it will be possible to alter English translation without a need to translate all other strings again. Also I think application locale and default locale can be not the same, meaning strings are written in English initially, but default locale can be German for example. So maybe there it's good to introduce new config variable like 'source_locale'. 

That's just some thoughts, decided to share with you.

**Comment by vedmant** [comment]
Hi, If you are interested, I also extended UrlGenerator function to():

    public function to($path, $extra = [], $secure = null)
    {
        // First we will check if the URL is already a valid URL. If it is we will not
        // try to generate a new one but will simply return the URL as is, which is
        // convenient since developers do not always have to check if it's valid.
        if ($this->isValidUrl($path)) {
            return $path;
        }

        $segments = array_filter(explode('/', $path));

        $first_segment = Arr::get($segments, 0);

        $locale = \Request::getLocale();

        // Get locale from url first segment
        if(in_array($first_segment, $this->locales)) {
            unset($segments[0]);
            $locale = $first_segment;
        }

        // Get locale from passed extra param
        if(isset($extra['locale'])) {
            $locale = $extra['locale'];
            unset($extra['locale']);
        }

        // Remove default locale
        if($locale == $this->default_locale) $locale = null;

        // Build new path if locale is present
        $path = implode('/', array_merge([$locale], $segments));

        return parent::to($path, $extra, $secure);
    }

This way it's possible to keep language prefixes on redirects and on any url.
