### ISSUE TITLE
Getting issue wtih String show � (questions marks) instead of characters

### ISSUE THREAD

**Issue by alpeshkasodariya** [stevebauman/translation#6]
Hello,
 
We are using getting character display issue with Gujarati and Hindi language lacoale.Getting below like output when we set bleow code in view file .

{{ _t('Inventory Menu', array(), 'gu')  }}

output getting like
????????

We have check it above with French locale then it is working fine but this issue getting on Gujarati and Hindi language.

Could you please help us for ?

Thanks in advanced.

Regards,
Alpeh

**Comment by stevebauman** [comment]
Hi, this has been fixed in the master build, just doing a couple more tweaks and I'll have another release out. Have you tried turning off `ucfirst` in the configuration?

**Comment by alpeshkasodariya** [comment]
Hi ,
Thanks for reply.

From where we can turning off ucfirst ?
I mean which configuration file we need to set  turning off ucfirst .

Regards,
Alpesh

**Comment by stevebauman** [comment]
In the translation.php configuration file, if you're on Laravel 5 or greater.

**Comment by alpeshkasodariya** [comment]
Yes, laravel 5

**Comment by alpeshkasodariya** [comment]
We need to set  'auto_translate_ucfirst' => false.
Right

**Comment by stevebauman** [comment]
That's correct, does that make any difference setting it to false? Make sure you clear the application cache as well.

**Comment by alpeshkasodariya** [comment]
Yes.
Many thanks.

Regards,
Alpesh

**Comment by stevebauman** [comment]
Great to hear! Not a problem at all.
