### ISSUE TITLE
Is translations case insensitive?

### ISSUE THREAD

**Issue by vedmant** [stevebauman/translation#7]
I just edited string in sources from "Customer registration" to "Customer Registration" but it doesn't make any effect, it pulls "Customer registration" from database until I remove that record from DB. I cleared cache with "cache:clear". So it looks like it ignores works case.

**Comment by stevebauman** [comment]
Yes I believe translations **are** case insensitive. Translations are created through a `firstOrCreate()` on the translation model, which is directly tied to Laravel.

https://github.com/stevebauman/translation/blob/master/src/Translation.php#L375

**Comment by vedmant** [comment]
Thanks, I saw this line. Just checked it again, strange thing that when I change from "Customer Registration" to "Customer registration" it added new record, but in opposite direction, from "Customer registration" to "Customer Registration" it still gets old record "Customer registration". Wierd.

**Comment by stevebauman** [comment]
No problem, but hmm it sounds like it could be a combination of Laravel and your database, but to be honest I'm really not sure. If I built in case sensitivity I'd need to use `DB::raw()`, however I really wouldn't like to require another dependency. `DB::raw()` also uses the default database connection which would cause issues.
