### ISSUE TITLE
Translations cache

### ISSUE THREAD

**Issue by vedmant** [stevebauman/translation#8]
Sorry for bothering again, but I noticed that it actually doen't cache all database query, for example when it pulls translated string http://screencast.com/t/Iyg5vxcje2 it makes query to DB for every string.  In debug bar I see a lot of queries http://screencast.com/t/yHrmt3OPg.

**Comment by stevebauman** [comment]
Yup you're right. Need to cache locales as well.

**Comment by neokike** [comment]
hi, first of all thank you for this amazing package, but my question is what is the status of this issue? thanks in advance.

**Comment by stevebauman** [comment]
Fixed by @loshmis https://github.com/stevebauman/translation/pull/12
