### ISSUE TITLE
Default locale

### ISSUE THREAD

**Issue by vedmant** [stevebauman/translation#9]
Hi, there are problems with this package, it's starting when I need to change App locale. I need that for using another package - https://github.com/dimsav/laravel-translatable , it uses App locale settings to translate models. So the actual problem is that when I change application locale your package starting to add different locale strings as default strings for translations, this is because it creates default translation based on App locale http://screencast.com/t/jIbIFGafc , I think this is not correct as I change App locale based on url value, like /en/ or /ch/. It should use default locale from config('translation.default'). I'll fork your package as I need to edit it, otherwise it doesn't work properly.

**Comment by stevebauman** [comment]
> It should use default locale from config('translation.default'). I'll fork your package as I need to edit it, otherwise it doesn't work properly.

I agree. Fixing now.

**Comment by stevebauman** [comment]
Closed with release `v1.3.1`
